# This Dockerfile is used to build an image containing basic stuff to be used as a Jenkins slave build node.
FROM ubuntu:16.04

ENV SONAR_RUNNER_VERSION 2.6.1
ENV SONAR_RUNNER_HOME /usr/local/sonar-scanner-${SONAR_RUNNER_VERSION}
ENV SONAR_RUNNER_PACKAGE sonar-scanner-${SONAR_RUNNER_VERSION}.zip

# Add locales after locale-gen as needed
# Upgrade packages on image
# Preparations for sshd
RUN locale-gen en_US.UTF-8 &&\
    apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew"  --no-install-recommends openssh-server &&\
    apt-get -q autoremove &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin &&\
    sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd &&\
    mkdir -p /var/run/sshd

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install JDK 8 (latest edition)
RUN apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew"  --no-install-recommends openjdk-8-jre-headless &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Install wget, python and unzip
RUN apt-get -q update &&\
  apt-get -q install -y python wget unzip git &&\
  apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Install nodejs
RUN wget -S -O - https://deb.nodesource.com/setup_6.x | bash - \
  && apt-get update \
  && apt-get install -y nodejs \
  && apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Install build-essential libzmq-dev for npm install zmq
RUN apt-get update \
  && apt-get install -y build-essential libzmq-dev \
  && apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Install sonarqube runner
WORKDIR /usr/local
RUN wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/${SONAR_RUNNER_PACKAGE} \
 && unzip ${SONAR_RUNNER_PACKAGE} \
 && rm ${SONAR_RUNNER_PACKAGE}

# Set user jenkins to the image
RUN useradd -m -d /home/jenkins -s /bin/sh jenkins &&\
    echo "jenkins:jenkins" | chpasswd

# Install package manager for nodejs
RUN npm install -g yarn

# copy oracle instant client libs
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient
RUN mkdir -p /opt/oracle
ADD tools/oracle/instantclient /opt/oracle/instantclient
# install libaio for oracle instant client
RUN apt-get update && \
  apt-get install -y libaio1 && \
  apt-get -q clean -y && \
  rm -rf /var/lib/apt/lists/* && \
  rm -f /var/cache/apt/*.bin

# Standard SSH port
EXPOSE 22

# Default command
CMD ["/usr/sbin/sshd", "-D"]
