import constants from 'flux-constants'

export default constants([
  // patient page
  'OVERVIEW_OVERVIEW_CHANGE_SHIFT',
  'OVERVIEW_OVERVIEW_CHANGE_SHIFT_FAILED',
  'OVERVIEW_OVERVIEW_CHANGE_CATEGORY',
  'OVERVIEW_OVERVIEW_CHANGE_CATEGORY_FAILED',
  'OVERVIEW_OVERVIEW_CHANGE_AREA',
  'OVERVIEW_OVERVIEW_CHANGE_AREA_FAILED',
  'OVERVIEW_OVERVIEW_CHANGE_BPCLASS',
  'OVERVIEW_OVERVIEW_CHANGE_BPCLASS_FAILED',
  'OVERVIEW_OVERVIEW_FETCHING',
  'OVERVIEW_OVERVIEW_SUCCESS',
  'OVERVIEW_OVERVIEW_FAILED',
  'OVERVIEW_ABNORMAL_LIST_FETCHING',
  'OVERVIEW_ABNORMAL_LIST_SUCCESS',
  'OVERVIEW_ABNORMAL_LIST_FAILED',
  'OVERVIEW_SHIFTS_FETCHING',
  'OVERVIEW_SHIFTS_SUCCESS',
  'OVERVIEW_SHIFTS_FAILED',
])
