FROM alpine:3.4

ENV VERSION=3.0.0

RUN apk --update --no-cache add curl jq libstdc++ && \
  apk --no-cache add --virtual .build-deps make cmake autoconf automake tar libtool g++ && \
  curl -o protobuf-${VERSION}.tar.gz -sSL https://github.com/google/protobuf/releases/download/v${VERSION}/protobuf-cpp-${VERSION}.tar.gz && \
  tar -zxvf protobuf-${VERSION}.tar.gz && \
  cd protobuf-${VERSION} && \
  ./autogen.sh && \
  ./configure --prefix=/usr && \
  make && \
  make install && \
  apk del .build-deps && \
  rm -rf /protobuf-${VERSION} /protobuf-${VERSION}.tar.gz /var/cache/apk/* /usr/lib/libproto*.a

ADD data/about.proto /about.proto
ADD data/update_license.sh /update_license.sh

ENTRYPOINT ["/update_license.sh"]
