import constants from 'flux-constants'

export default constants([
  // universal
  'UNIVERSAL_SET_TOKEN',

  // application level constants
  'APP_LOADING',
  'APP_UPDATE_TIME',
  'APP_SET_TIMEOUT',
  'APP_NOTIFICATION',
  'APP_NOTIFICATION_GREEN',
  'APP_NOTIFICATION_RED',
  'APP_SET_MODAL',
  'APP_LOCATION_CHANGE',
  'APP_SET_LICENSE_STATUS',

  // locale
  'LOCALE_SET_SWITCH', // to saga
  'LOCALE_SWITCH', // to reducer

  // fetch related
  'SAGA_FETCH_ACTION',
  'SAGA_CUSTOM_TASK',
  'SAGA_PRELOAD_ACTION',
  'REFRESH_TOKEN_DONE',

  // auth related
  'LOGOUT_REQUESTING',
  'LOGOUT_SUCCESS',
  'LOGOUT_FAILED',
  'AUTH_UNAUTHENTICATED',

  // selected patient
  'PATIENT_SELECT_PATIENT',
  'PATIENT_SELECT_RECORD',

   // // patient page
  'FETCH_RECORD_LIST_REQUEST',
  'FETCH_RECORD_LIST_SUCCESS',
  'FETCH_RECORD_LIST_FAILED',
  'FETCH_PATIENT_REQUEST',
  'FETCH_PATIENT_SUCCESS',
  'FETCH_PATIENT_FAILED',

  'PAGE_CANCEL_POLLING',
])

export const BUSY_SOURCES = constants([
  'EFFECTIVE_PRELOAD',
  'EFFECTIVE_FETCH_LIST',
  'EFFECTIVE_CHANGE_LIBS',
  'DASHBOARD_PRELOAD',
  'EXAM_PRELOAD',
  'EXAM_FETCH_TEST_RESULT',
  'EXAM_TEST_ITEM_LIST',
  'EXAM_POLLING_TASK', // add additional enable busy
  'LOGIN',
  'OVERVIEW_PRELOAD',
  'OVERVIEW_CHANGE_SHIFT',
  'OVERVIEW_CHANGE_CATEGORY',
  'OVERVIEW_CHANGE_BPCLASS',
  'OVERVIEW_CHANGE_AREA',
  'OVERVEIW_FETCH_SHIFT',
  'OVERVEIW_FETCH_OVERVIEW',
  'OVERVIEW_FETCH_ABNORMAL',
  'OVERVIEW_POLLING_TASK', // add additional enable busy
  'OVERVIEW_SEARCH_PRELOAD',
  'OVERVIEW_SEARCH_FETCH_SCHEDULE',
  'RECORD_PRELOAD',
  'RISK_ESTIMATION_PRELOAD',
  'RISK_ESTIMATION_SIMULATE',
  'RISK_PROBABILITY_PRELOAD',
  'RISK_PROBABILITY_SIMULATE',
  'RISK_RANGE_PRELAOD',
  'RISK_RANGE_SIMULATE',
  'RISK_PRELOAD',
  'RISK_CHECK_ACCESS_RISK_CHART', // add additional enable busy
  'RISK_FETCH_ALARM_PHRASE_LIST',
  'RISK_SUBMIT_ALARM_PHARSE',
  'RISK_SET_ALARM_KEEP_OBSERVE',
  'SAGA_FETCHING_TASK',
  'SAGA_POLLING_TASK',
  'SET_PERAONAL_THRESHOLD',
])
