import constants from 'flux-constants'

export default constants([
  'RISK_SBP_SELECT_TIME',
  'RISK_SBP_VARIATION_PRELOAD',
  'RISK_SBP_SIMULATE_REQUEST',
  'RISK_SBP_SIMULATE_SUCCESS',
  'RISK_SBP_SIMULATE_FAILED',
  'RISK_CLEAR_SIMULATION',
  'RISK_SBP_REFRESH_DATA',
  'PERSONAL_SYSTEM_THRESHOLD_REQUEST',
  'PERSONAL_SYSTEM_THRESHOLD_SUCCESS',
  'PERSONAL_SYSTEM_THRESHOLD_FAILED',
  'SET_PERSONAL_THRESHOLD_REQUEST',
  'SET_PERSONAL_THRESHOLD_SUCCESS',
  'SET_PERSONAL_THRESHOLD_FAILED',
  'UPDATE_SYSTEM_THRESHOLD_SUCCESS',
])
