import constants from 'flux-constants'

export default constants([
  'FETCH_RECORD_DETAIL_REQUEST',
  'FETCH_RECORD_DETAIL_SUCCESS',
  'FETCH_RECORD_DETAIL_FAILED',
  'REFRESH_RECORD_DETAIL_SUCCESS',
  'RECORD_TOGGLE_PARAM',
  'RECORD_SELECT_TIME',
])
