import React, { Component } from 'react'

export default class extends Component {
  render() {
    return (

<div>
  <div>
    <div>
      <div>
        <p><strong>PLEASE READ CAREFULLY BEFORE USING THIS SOFTWARE PRODUCT:</strong> This End-User License Agreement (“EULA”) is a legal agreement between (a) you (either an individual or a single entity) and (b) Wistron Corporation (“WISTRON”) that governs your use of any Software Product, installed on or made available by WISTRON.</p>
        <p><strong>BY CLICKING “I AGREE”, OR BY TAKING ANY STEP TO INSTALL OR USE THE SOFTWARE PRODUCT, YOU AGREE TO BE BOUND BY THE TERMS OF THIS EULA. IF YOU DO NOT ACCEPT THE EULA TERMS, CLICK “DISAGREE” OR DO NOT USE THE SOFTWARE PRODUCT. </strong></p>
        <ol>
      <li><strong>GRANT OF LICENSE.</strong> The Software Product includes two types of computer software (1) software that is owned by WISTRON (and may include associated media, and “online” or electronic documentation) (collectively the “Software Product”) and (2) other software provided by third parties and used with the Software Product (“Third Party Software”). WISTRON grants you the following non-exclusive, non-transferable, non-sublicensable, limited right provided you agree to and comply with all terms and conditions of this EULA:
        <ol>
          <li>You may use the Software Product on your computer or mobile device system (or computers if the Software Product is sold to you for use on multiple computers). You may not use the Software Product on additional computers and do not have the right to distribute the Software Product. You agree to only use the Software Product as expressly permitted herein.</li>
          <li>You may not rent, lease or lend the Software Product or use the Software Product for commercial timesharing or bureau use. You may not sublicense, assign or transfer the license or Software Product except as expressly provided in this EULA.</li>
          <li><strong>Limitation on Reverse Engineering.</strong> Except to the extent that such restriction is not permitted under applicable law, you are not permitted (and you agree not to) reverse engineer, decompile, disassemble or create derivative works of or modify the Software Product. Nothing contained herein shall be construed, expressly or implicitly, as transferring any right, license or title to you other than those explicitly granted under this EULA. WISTRON reserves all rights in its intellectual property rights not expressly agreed to herein. Unauthorized copying of the Software Product or failure to comply with the restrictions in this EULA (or other breach of the license herein) will result in automatic termination of this EULA and you agree that it will constitute immediate, irreparable harm to WISTRON for which monetary damages would be an inadequate remedy, and that injunctive relief will be an appropriate remedy for such breach.</li>
          <li><strong>Reservation of Rights.</strong> The Software Product is licensed, not sold, to you by WISTRON. WISTRON and its suppliers own all right, title and interest in and to the Software Product and reserve all rights not expressly granted to you in this EULA. You agree to refrain from any action that would diminish such rights or would call them into question.</li>
          <li><strong>Third Party Software.</strong> Notwithstanding the terms and conditions of this EULA, all or any portion of the Software Product which constitutes Third Party Software, is licensed to you subject to the terms and conditions of the software license agreement accompanying such Third Party Software whether in the form of a discrete agreement, shrink wrap license or electronic license terms accepted at time of download. Use of the Third Party Software by you shall be governed entirely by the terms and conditions of such license.</li>
        </ol>
      </li>
      <li><strong>INTELLECTUAL PROPRIETARY RIGHTS.</strong> All intellectual property rights in the Software Product and user documentation are owned by WISTRON or its suppliers and are protected by law, including but not limited to copyright, trade secret, and trademark law, as well as other applicable laws and international treaty provisions. The structure, organization and code of the Software Product are the valuable trade secrets and confidential information of WISTRON and its suppliers. You shall not remove any product identification, copyright notices or proprietary restrictions from the Software Product.</li>
      <li><strong>CONSENT TO USE OF DATA.</strong> You agree that WISTRON may collect and use technical data and related information, including but not limited to technical information about your device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support and other services to you (if any) related to the Software Product. Wistron may use this information, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you as needed.</li>
      <li>This EULA is effective unless terminated or rejected. This EULA will also terminate immediately and without additional notice in the event you breach this EULA and/or fail to comply with any term or condition of this EULA.</li>
      <li><strong>DISCLAIMER OF WARRANTIES.</strong>
        <ol>
          <li>To the maximum extent permitted under applicable law, the Software Product is offered on an “AS-IS” basis and WISTRON does NOT warrant that the functions contained in the Software Product will meet your requirements or that the operation of the Software Product will be uninterrupted or error free or that such errors will be corrected. Computer software is inherently subject to bugs and potential incompatibility with other computer software and hardware. You should not use the Software Product for any applications in which failure could cause any significant damage or injury to persons or tangible or intangible property.</li>
          <li>EXCEPT AS MAY BE SET OUT IN A SPECIFIC WARRANTY ACCOMPANYING THE SOFTWARE PRODUCT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WISTRON AND ITS SUPPLIERS PROVIDE THE SOFTWARE PRODUCT AND THIRD PARTY SOFTWARE “AS IS” AND WITH ALL FAULTS AND WITHOUT ANY OTHER WARRANTY OF ANY KIND, AND HEREBY DISCLAIM ALL OTHER WARRANTIES AND CONDITIONS, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE AND NON-INFRINGEMENT, ANY IMPLIED WARRANTIES, DUTIES OR CONDITIONS OF MERCHANTABILITY, OF FITNESS FOR A PARTICULAR PURPOSE, AND OF LACK OF VIRUSES ALL WITH REGARD TO THE SOFTWARE PRODUCT AND THIRD PARTY SOFTWARE. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY WISTRON OR A WISTRON AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. Some states/jurisdictions do not allow exclusion of implied warranties or limitations on the duration of implied warranties, so the above disclaimer may not apply to you in its entirety. To the extent applicable law requires WISTRON to provide warranties, you agree that the scope and duration of such warranty shall be to the minimum extent permitted under such applicable law.</li>
          <li>IN NO EVENT DOES WISTRON PROVIDE ANY WARRANTY OR REPRESENTATIONS WITH RESPECT TO ANY THIRD PARTY HARDWARE OR SOFTWARE WITH WHICH THE SOFTWARE PRODUCT IS DESIGNED TO BE USED, AND WISTRON DISCLAIMS ALL LIABILITY WITH RESPECT TO ANY FAILURES THEREOF.</li>
        </ol>
      </li>
  <li><strong>LIMITATION OF LIABILITY. </strong>Notwithstanding any damages that you might incur, the entire liability of WISTRON and any of its suppliers under any provision of this EULA and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the Software Product. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WISTRON OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, FOR LOSS OF DATA OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, FOR PERSONAL INJURY, FOR LOSS OF PRIVACY ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF OR INABILITY TO USE THE SOFTWARE PRODUCT, THIRD PARTY SOFTWARE AND/OR THIRD PARTY HARDWARE USED WITH THE SOFTWARE PRODUCT, OR OTHERWISE IN CONNECTION WITH ANY PROVISION OF THIS EULA), EVEN IF WISTRON OR ANY SUPPLIER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF THE REMEDY FAILS OF ITS ESSENTIAL PURPOSE. Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</li>
  <li>You agree to indemnify and hold WISTRON and its officers, directors, employees and licensors harmless from any claim or demand (including but not limited to reasonable legal fees) made by a third party due to or arising out of or related to your violation of the terms and conditions of this EULA, your violation of any laws, regulations or third party rights or your negligent act, omission or willful misconduct.</li>
  <li><strong>COMPLIANCE WITH LAWS.</strong> You shall comply with all laws and regulations of the Taiwan and other countries (“Export Laws”) to ensure that the Software Product is not exported, directly or indirectly, in violation of Export Laws, or used for any purpose prohibited by Export Laws, including, without limitation, nuclear, chemical, or biological weapons proliferation. You further agree that you will not use the Software Product for any purpose prohibited under applicable law.</li>
  <li><strong>GOVERNING LAW.</strong> This EULA is governed by the laws of Taiwan, R.O.C. exclusive of conflict of law provisions and you attorn to the jurisdiction of the Taipei District Courts in Taiwan with respect to any proceedings arising from this EULA. The parties hereby agree that this EULA is not governed by the United Nations Convention on Contracts for the International Sale of Goods.</li>
  <li><strong>ENTIRE AGREEMENT.</strong> This EULA is the entire agreement between you and WISTRON relating to the Software Product and it supersedes all prior or contemporaneous oral or written communications, proposals and representations with respect to the Software Product or any other subject matter covered by this EULA. In the event of a conflict between the English and any non-English versions of this EULA, the English version shall govern. If any provision of this EULA is held by a court of competent jurisdiction to be contrary to law, such provision will be changed and interpreted so as to best accomplish the objectives of the original provision to the fullest extent allowed by law and the remaining provision of the EULA will remain in force and effect.</li>
  </ol>
  <p>© 2015 Wistron Corporation. All rights reserved.<br/>
  Rev. 02/15</p>
      </div>
  </div>
  <div>
    <hr/>
  </div>
    </div>
    </div>
    )
  }
}
