import constants from 'flux-constants'

export default constants([
  'RISK_ALARM_PHARSE_FETCH_REQUEST',
  'RISK_ALARM_PHARSE_FETCH_SUCCESS',
  'RISK_ALARM_PHARSE_FETCH_FAILED',
  'RISK_ALARM_PHARSE_SUBMIT_REQUEST',
  'RISK_ALARM_PHARSE_SUBMIT_SUCCESS',
  'RISK_ALARM_PHARSE_SUBMIT_FAILED',
])
