import constants from 'flux-constants'

export default constants([
    // exam
  'SEARCHES_PATIENTS_TEST_RESULTS_INVALID',
  'SEARCHES_PATIENTS_ITEMS_LIST_UPDATE',
  'SEARCHES_PATIENTS_TEST_RESULTS_FETCHING',
  'SEARCHES_PATIENTS_TEST_RESULTS_SUCCESS',
  'SEARCHES_PATIENTS_TEST_RESULTS_FAILED',
  'SEARCHES_PATIENTS_ITEMS_LIST_FETCHING',
  'SEARCHES_PATIENTS_ITEMS_LIST_SUCCESS',
  'SEARCHES_PATIENTS_ITEMS_LIST_FAILED',
])
