import constants from 'flux-constants'

export default constants([
  'ADMIN_GET_LOGS',
  'ADMIN_GET_SETTING_REQUEST',
  'ADMIN_SET_TIMEOUT_SUCCESS',
  'ADMIN_SET_TIMEOUT_FAILED',
  'ADMIN_GET_SETTING_REQUEST',
  'ADMIN_GET_SETTING_SUCCESS',
  'ADMIN_GET_SETTING_FAILED',
  'ADMIN_GET_THRESHOLD_SETTING_REQUEST',
  'ADMIN_GET_THRESHOLD_SETTING_SUCCESS',
  'ADMIN_GET_THRESHOLD_SETTING_FAILED',
  'ADMIN_SET_THRESHOLD_SETTING_REQUEST',
  'ADMIN_SET_THRESHOLD_SETTING_SUCCESS',
  'ADMIN_SET_THRESHOLD_SETTING_FAILED',
])
